#!/usr/bin/env bash
# set up load balancer
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-1.8
sudo apt-get -y update
sudo apt-get -y install haproxy

sudo sed -i -e '$aENABLED=1\n' /etc/default/haproxy 
sudo sed -i -e '$a\listen http-in\n\tbind :80\n\tbalance roundrobin\n\tserver 31759-web-01 34.207.61.106:80 check\n\tserver 31759-web-02 100.25.169.163:80 check\n' /etc/haproxy/haproxy.cfg
sudo service haproxy restart
